version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: cryptobot-devcontainer
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      - devcontainer-extensions:/home/vscode/.vscode-server/extensions
      - devcontainer-insiders:/home/vscode/.vscode-server-insiders
      - bash-history:/commandhistory
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CryptoBot;User Id=sa;Password=CryptoBot@2024!;
      - Redis__ConnectionString=redis:6379
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      - HISTFILE=/commandhistory/.bash_history
    networks:
      - cryptobot-network
    depends_on:
      - sqlserver
      - redis
    user: vscode
    working_dir: /workspace

volumes:
  devcontainer-extensions:
  devcontainer-insiders:
  bash-history: